// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai-generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-generate.post').default>>>>
    }
    '/api/auth': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/security/setup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/security/setup.post').default>>>>
    }
    '/api/security/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/security/verify.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}