import {board, aiBuild, siteCopy} from './boards'
import {
  project,
  job,
  track,
  tool,
  cert,
  profilePhoto,
  caseStudyImage,
  caseStudyFigureFull,
  caseStudyFigurePair,
  caseStudyFigureTriptych,
  caseStudyMeta,
  caseStudyStat,
  caseStudyQuote,
  caseStudyShipped,
  caseStudyTone,
  caseStudySection,
} from './content'

export const schemaTypes = [
  board,
  aiBuild,
  siteCopy,
  project,
  job,
  track,
  tool,
  cert,
  profilePhoto,
  caseStudyImage,
  caseStudyFigureFull,
  caseStudyFigurePair,
  caseStudyFigureTriptych,
  caseStudyMeta,
  caseStudyStat,
  caseStudyQuote,
  caseStudyShipped,
  caseStudyTone,
  caseStudySection,
]
